import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name:'Atiq',
      phone: '01880901380',
      email:'atiqbabu1993@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name:'Misbah',
      phone: '01986809850',
      email:'example@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  books: [
    {
      name: 'Ana Franker Diary',
      category: 'Books',
      image: 'images_books/01.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'A',
      rating: 4.5,
      numReviews: 30,
      address: 'Banglabazar',
      writer: 'Perth Chatterjee',
    },
    {
      name: 'Theory of relativity',
      category: 'Books',
      image: 'images_books/02.jpg',
      price: 100,
      countInStock: 0,
      shopname: 'A',
      rating: 4.0,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Muhammad Zafor Iqbal'
    },
    {
      name: 'Income korun youtube theke',
      category: 'Books',
      image: 'images_books/03.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'C',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Pollob Shahriar'
    },
    {
      name: 'Ar-Rahekul Makhtum',
      category: 'Books',
      image: 'images_books/04.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'D',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Translated'
    },
    {
      name: 'Taranath Tantrik',
      category: 'Books',
      image: 'images_books/05.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      writer: 'Bibhutivushan Bandyepadhyay'
    },
    {
      name: 'Shikarer Bichitro Kahini',
      category: 'Books',
      image: 'images_books/06.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'F',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Debiproshad Bandyepadhyay'
    },
    {
      name: 'Bishad Shindhu',
      category: 'Books',
      image: 'images_books/07.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'A',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Mir Mosharraf Hossain'
    },
    {
      name: 'Uralponkhi',
      category: 'Books',
      image: 'images_books/08.jpg',
      price: 100,
      countInStock: 20,
      shopname: 'A',
      rating: 4.0,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Humayun Ahmed'
    },
    {
      name: 'English to Bengali Dictionary',
      category: 'Books',
      image: 'images_books/09.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'C',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Bangla Academy'
    },
    {
      name: 'Bengali to English Dictionary',
      category: 'Books',
      image: 'images_books/10.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'D',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Bangla Academy'
    },
    {
      name: 'Chader Pahar',
      category: 'Books',
      image: 'images_books/11.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Bibhutivushan Bandyepadhyay'
    },
    {
      name: 'Western Nirjonbash',
      category: 'Books',
      image: 'images_books/12.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'F',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Rokib Hasan'
    },
    {
      name: 'Engrejite zero to hero',
      category: 'Books',
      image: 'images_books/13.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'A',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Unknown'
    },
    {
      name: 'Toslima Nasrin Kobita Shomogro',
      category: 'Books',
      image: 'images_books/14.jpg',
      price: 100,
      countInStock: 20,
      shopname: 'A',
      rating: 4.0,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Toslima Nasrin'
    },
    {
      name: 'Alexander the great',
      category: 'Books',
      image: 'images_books/15.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'C',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Ahmed Riaz'
    },
    {
      name: 'Dada Shomogro',
      category: 'Books',
      image: 'images_books/16.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'D',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Tarapod Ray'
    },
    {
      name: 'Kiriti Omnibash',
      category: 'Books',
      image: 'images_books/17.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Nihar-Ronjon Gupta'
    },
    {
      name: 'Misir Ali Shomogro',
      category: 'Books',
      image: 'images_books/18.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'F',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Humayun Ahmed'
    },
    {
      name: 'Harry Potter',
      category: 'Books',
      image: 'images_books/19.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'J.K. Rowling'
    },
    {
      name: 'Chokher Bali',
      category: 'Books',
      image: 'images_books/20.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'F',
      rating: 4.5,
      numReviews: 10,
      address: 'Banglabazar',
      writer: 'Rabindronath Tagore'
    },
    {
      name: 'Shonar Bangla',
      category: 'Books',
      image: 'images_books/21.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'A',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Narayon Shannal'
    },
    {
      name: 'Himu Mama',
      category: 'Books',
      image: 'images_books/22.jpg',
      price: 100,
      countInStock: 20,
      shopname: 'A',
      rating: 4.0,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Humayun Ahmed'
    },
    {
      name: 'Amar Bangla Boi',
      category: 'Books',
      image: 'images_books/23.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'C',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Bangladesh Board'
    },
    {
      name: 'AdorshoLipi',
      category: 'Books',
      image: 'images_books/24.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'D',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Unknown'
    },
    {
      name: 'Sherlock Holmes',
      category: 'Books',
      image: 'images_books/25.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Translated'
    },/*
    {
      name: 'Kobi',
      category: 'Books',
      image: 'images_books/26.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'F',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Tarashonkor Bandyepadhyay'
    },*/
    {
      name: 'SrimodVogobod Gita',
      category: 'Books',
      image: 'images_books/27.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'A',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Unknown'
    },
    {
      name: 'Rich dad, poor dad',
      category: 'Books',
      image: 'images_books/28.jpg',
      price: 100,
      countInStock: 20,
      shopname: 'A',
      rating: 4.0,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Robert T Kiosoky'
    },
    {
      name: 'Byomkesh',
      category: 'Books',
      image: 'images_books/29.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'C',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Shorodindu Bandyepadhyay'
    },
    {
      name: 'Podda Nodir Majhi',
      category: 'Books',
      image: 'images_books/30.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'D',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Manik Bandyepadhyay'
    },
    {
      name: 'Pother Pechali',
      category: 'Books',
      image: 'images_books/31.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Bibhutivushan Bandyepadhyay'
    },/*
  {
    name: 'Shonar Bangla',
    category: 'Books',
    image: 'images_books/32.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'A',
    rating: 4.5,
    numReviews: 10,
    address: 'Nilkhet',
    writer: 'Narayon Shannal'
  },*/
  {
    name: 'Khoma koro Shuvash',
    category: 'Books',
    image: 'images_books/33.jpg',
    price: 100,
    countInStock: 20,
    shopname: 'A',
    rating: 4.0,
    numReviews: 10,
    address: 'Nilkhet',
    writer: 'Dr. Joyont Chowdhury'
  },
  {
    name: 'Shinghobahini',
    category: 'Books',
    image: 'images_books/34.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'C',
    rating: 4.5,
    numReviews: 10,
    address: 'Nilkhet',
    writer: 'Shomoresh Majumdar'
  },
  {
    name: 'Misir Ali Omnibas',
    category: 'Books',
    image: 'images_books/35.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'D',
    rating: 4.5,
    numReviews: 10,
    address: 'Nilkhet',
    writer: 'Humayun Ahmed'
  },
  {
    name: 'Quranul Karim',
    category: 'Books',
    image: 'images_books/36.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'E',
    rating: 4.5,
    numReviews: 10,
    address: 'Nilkhet',
    writer: 'Unknown'
  },
  {
    name: 'Kobi',
    category: 'Books',
    image: 'images_books/37.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'F',
    rating: 4.5,
    numReviews: 10,
    address: 'Nilkhet',
    writer: 'Budhodeb Guho'
  },
  {
    name: 'Lalshalu',
    category: 'Books',
    image: 'images_books/38.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'E',
    rating: 4.5,
    numReviews: 10,
    address: 'Nilkhet',
    writer: 'Syed Oali-ullah'
  },
  {
    name: 'Meghdut',
    category: 'Books',
    image: 'images_books/39.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'F',
    rating: 4.5,
    numReviews: 10,
    address: 'Nilkhet',
    writer: 'Kalidash'
  },
  {
    name: 'Chacha Kahini',
    category: 'Books',
    image: 'images_books/40.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'A',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Syed Mujtaba Ali'
  },
  {
    name: 'Ekattorer Dinguli',
    category: 'Books',
    image: 'images_books/41.jpg',
    price: 100,
    countInStock: 20,
    shopname: 'A',
    rating: 4.0,
    numReviews: 10,
    address: 'Other',
    writer: 'Jahanara Imam'
  },
  {
    name: 'Mejodidi',
    category: 'Books',
    image: 'images_books/42.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'C',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Sharotchandra Chatterjee'
  },
  {
    name: 'Lojja',
    category: 'Books',
    image: 'images_books/43.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'D',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Toslima Nasrin'
  },
  {
    name: 'Shonku Shomogro',
    category: 'Books',
    image: 'images_books/44.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'E',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Shattajit Ray'
  },
  {
    name: 'Abu Is-hak golpo shomogro',
    category: 'Books',
    image: 'images_books/45.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'F',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Abu Is-hak'
  },
  {
    name: 'Batul Shomogro',
    category: 'Books',
    image: 'images_books/46.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'A',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Narayon Debnath'
  },
  {
    name: 'Professor Hijibijbij',
    category: 'Books',
    image: 'images_books/47.jpg',
    price: 100,
    countInStock: 20,
    shopname: 'A',
    rating: 4.0,
    numReviews: 10,
    address: 'Other',
    writer: 'Shattajit Ray'
  },
  {
    name: 'Nat Boltu',
    category: 'Books',
    image: 'images_books/48.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'C',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Muhammad Zafor Iqbal'
  },
  {
    name: 'Hajar bosor dhore',
    category: 'Books',
    image: 'images_books/49.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'D',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Johir Rayhan'
  },
  {
    name: 'Ma',
    category: 'Books',
    image: 'images_books/50.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'E',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Anisul Huq'
  },
  {
    name: 'The Hobbit',
    category: 'Books',
    image: 'images_books/51.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'F',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'J.R.R. Tolkien'
  },
  {
    name: 'The Da Vinci Code',
    category: 'Books',
    image: 'images_books/52.jpg',
    price: 120,
    countInStock: 10,
    shopname: 'A',
    rating: 4.5,
    numReviews: 10,
    address: 'Other',
    writer: 'Dan Brown'
  }
  ],
};
export default data;
