const data = {
    books: [
      {
        _id: '1',
        name: 'Ana Franker Diary',
        category: 'Books',
        image: 'images_books/01.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'A',
        rating: 4.5,
        numReviews: 30,
        address: 'Banglabazar',
        writer: 'Perth Chatterjee',
      },
      {
        _id: '2',
        name: 'Theory of relativity',
        category: 'Books',
        image: 'images_books/02.jpg',
        price: 100,
        countInStock: 0,
        shopname: 'A',
        brand: 'B',
        rating: 4.0,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Muhammad Zafor Iqbal'
      },
      {
        _id: '3',
        name: 'Income korun youtube theke',
        category: 'Books',
        image: 'images_books/03.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'C',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Pollob Shahriar'
      },
      {
        _id: '4',
        name: 'Ar-Rahekul Makhtum',
        category: 'Books',
        image: 'images_books/04.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'D',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Translated'
      },
      {
        _id: '5',
        name: 'Taranath Tantrik',
        category: 'Books',
        image: 'images_books/05.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'E',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Bibhutivushan Bandyapaddhay'
      },
      {
        _id: '6',
        name: 'Shikarer Bichitro Kahini',
        category: 'Books',
        image: 'images_books/06.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'F',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Debiproshad Bandyapaddhay'
      },
      {
        _id: '7',
        name: 'Bishad Shindhu',
        category: 'Books',
        image: 'images_books/07.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'A',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Mir Mosharraf Hossain'
      },
      {
        _id: '8',
        name: 'Uralponkhi',
        category: 'Books',
        image: 'images_books/08.jpg',
        price: 100,
        countInStock: 20,
        shopname: 'A',
        brand: 'B',
        rating: 4.0,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Humayun Ahmed'
      },
      {
        _id: '9',
        name: 'English to Bengali Dictionary',
        category: 'Books',
        image: 'images_books/09.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'C',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Bangla Academy'
      },
      {
        _id: '10',
        name: 'Bengali to English Dictionary',
        category: 'Books',
        image: 'images_books/10.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'D',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Bangla Academy'
      },
      {
        _id: '11',
        name: 'Chader Pahar',
        category: 'Books',
        image: 'images_books/11.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'E',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Bibhutivushan Bandyapaddhay'
      },
      {
        _id: '12',
        name: 'Western Nirjonbash',
        category: 'Books',
        image: 'images_books/12.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'F',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Rokib Hasan'
      },
      {
        _id: '13',
        name: 'Engrejite zero to hero',
        category: 'Books',
        image: 'images_books/13.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'A',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Unknown'
      },
      {
        _id: '14',
        name: 'Toslima Nasrin Kobita Shomogro',
        category: 'Books',
        image: 'images_books/14.jpg',
        price: 100,
        countInStock: 20,
        shopname: 'A',
        brand: 'B',
        rating: 4.0,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Toslima Nasrin'
      },
      {
        _id: '15',
        name: 'Alexander the great',
        category: 'Books',
        image: 'images_books/15.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'C',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Ahmed Riaz'
      },
      {
        _id: '16',
        name: 'Dada Shomogro',
        category: 'Books',
        image: 'images_books/16.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'D',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Tarapod Ray'
      },
      {
        _id: '17',
        name: 'Kiriti Omnibash',
        category: 'Books',
        image: 'images_books/17.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'E',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Nihar-Ronjon Gupta'
      },
      {
        _id: '18',
        name: 'Misir Ali Shomogro',
        category: 'Books',
        image: 'images_books/18.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'F',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Humayun Ahmed'
      },
      {
        _id: '19',
        name: 'Harry Potter',
        category: 'Books',
        image: 'images_books/19.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'E',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'J.K. Rowling'
      },
      {
        _id: '20',
        name: 'Chokher Bali',
        category: 'Books',
        image: 'images_books/20.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'F',
        rating: 4.5,
        numReviews: 10,
        address: 'Banglabazar',
        writer: 'Rabindronath Tagore'
      },
      {
        _id: '21',
        name: 'Shonar Bangla',
        category: 'Books',
        image: 'images_books/21.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'A',
        rating: 4.5,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Narayon Shannal'
      },
      {
        _id: '22',
        name: 'Himu Mama',
        category: 'Books',
        image: 'images_books/22.jpg',
        price: 100,
        countInStock: 20,
        shopname: 'A',
        brand: 'B',
        rating: 4.0,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Humayun Ahmed'
      },
      {
        _id: '23',
        name: 'Amar Bangla Boi',
        category: 'Books',
        image: 'images_books/23.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'C',
        rating: 4.5,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Bangladesh Board'
      },
      {
        _id: '24',
        name: 'AdorshoLipi',
        category: 'Books',
        image: 'images_books/24.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'D',
        rating: 4.5,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Unknown'
      },
      {
        _id: '25',
        name: 'Sherlock Holmes',
        category: 'Books',
        image: 'images_books/25.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'E',
        rating: 4.5,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Translated'
      },
      {
        _id: '26',
        name: 'Kobi',
        category: 'Books',
        image: 'images_books/26.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'F',
        rating: 4.5,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Tarashonkor Bandyapaddhay'
      },
      {
        _id: '27',
        name: 'SrimodVogobod Gita',
        category: 'Books',
        image: 'images_books/27.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'A',
        rating: 4.5,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Unknown'
      },
      {
        _id: '28',
        name: 'Rich dad, poor dad',
        category: 'Books',
        image: 'images_books/28.jpg',
        price: 100,
        countInStock: 20,
        shopname: 'A',
        brand: 'B',
        rating: 4.0,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Robert T Kiosoky'
      },
      {
        _id: '29',
        name: 'Byomkesh',
        category: 'Books',
        image: 'images_books/29.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'C',
        rating: 4.5,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Shorodindu Bandyapaddhay'
      },
      {
        _id: '30',
        name: 'Podda Nodir Majhi',
        category: 'Books',
        image: 'images_books/30.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'D',
        rating: 4.5,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Manik Bandyapaddhay'
      },
      {
        _id: '31',
        name: 'Pother Pechali',
        category: 'Books',
        image: 'images_books/31.jpg',
        price: 120,
        countInStock: 10,
        shopname: 'E',
        rating: 4.5,
        numReviews: 10,
        address: 'Nilkhet',
        writer: 'Bibhutivushan Bandyapaddhay'
      },
    {
      _id: '32',
      name: 'Shonar Bangla',
      category: 'Books',
      image: 'images_books/32.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'A',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Narayon Shannal'
    },
    {
      _id: '33',
      name: 'Khoma koro Shuvash',
      category: 'Books',
      image: 'images_books/33.jpg',
      price: 100,
      countInStock: 20,
      shopname: 'A',
      brand: 'B',
      rating: 4.0,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Dr. Joyont Chowdhury'
    },
    {
      _id: '34',
      name: 'Shinghobahini',
      category: 'Books',
      image: 'images_books/34.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'C',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Shomoresh Majumdar'
    },
    {
      _id: '35',
      name: 'Misir Ali Omnibas',
      category: 'Books',
      image: 'images_books/35.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'D',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Humayun Ahmed'
    },
    {
      _id: '36',
      name: 'Quranul Karim',
      category: 'Books',
      image: 'images_books/36.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Unknown'
    },
    {
      _id: '37',
      name: 'Kobi',
      category: 'Books',
      image: 'images_books/37.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'F',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Budhodeb Guho'
    },
    {
      _id: '38',
      name: 'Lalshalu',
      category: 'Books',
      image: 'images_books/38.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Syed Oali-ullah'
    },
    {
      _id: '39',
      name: 'Meghdut',
      category: 'Books',
      image: 'images_books/39.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'F',
      rating: 4.5,
      numReviews: 10,
      address: 'Nilkhet',
      writer: 'Kalidash'
    },
    {
      _id: '40',
      name: 'Chacha Kahini',
      category: 'Books',
      image: 'images_books/40.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'A',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Syed Mujtaba Ali'
    },
    {
      _id: '41',
      name: 'Ekattorer Dinguli',
      category: 'Books',
      image: 'images_books/41.jpg',
      price: 100,
      countInStock: 20,
      shopname: 'A',
      brand: 'B',
      rating: 4.0,
      numReviews: 10,
      address: 'Other',
      writer: 'Jahanara Imam'
    },
    {
      _id: '42',
      name: 'Mejodidi',
      category: 'Books',
      image: 'images_books/42.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'C',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Sharotchandra Chattapaddhay'
    },
    {
      _id: '43',
      name: 'Lojja',
      category: 'Books',
      image: 'images_books/43.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'D',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Toslima Nasrin'
    },
    {
      _id: '44',
      name: 'Shonku Shomogro',
      category: 'Books',
      image: 'images_books/44.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Shattajit Ray'
    },
    {
      _id: '45',
      name: 'Abu Is-hak golpo shomogro',
      category: 'Books',
      image: 'images_books/45.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'F',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Abu Is-hak'
    },
    {
      _id: '46',
      name: 'Batul Shomogro',
      category: 'Books',
      image: 'images_books/46.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'A',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Narayon Debnath'
    },
    {
      _id: '47',
      name: 'Professor Hijibijbij',
      category: 'Books',
      image: 'images_books/47.jpg',
      price: 100,
      countInStock: 20,
      shopname: 'A',
      brand: 'B',
      rating: 4.0,
      numReviews: 10,
      address: 'Other',
      writer: 'Shattajit Ray'
    },
    {
      _id: '48',
      name: 'Nat Boltu',
      category: 'Books',
      image: 'images_books/48.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'C',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Muhammad Zafor Iqbal'
    },
    {
      _id: '49',
      name: 'Hajar bosor dhore',
      category: 'Books',
      image: 'images_books/49.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'D',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Johir Rayhan'
    },
    {
      _id: '50',
      name: 'Ma',
      category: 'Books',
      image: 'images_books/50.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'E',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Anisul Huq'
    },
    {
      _id: '51',
      name: 'The Hobbit',
      category: 'Books',
      image: 'images_books/51.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'F',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'J.R.R. Tolkien'
    },
    {
      _id: '52',
      name: 'The Da Vinci Code',
      category: 'Books',
      image: 'images_books/52.jpg',
      price: 120,
      countInStock: 10,
      shopname: 'A',
      rating: 4.5,
      numReviews: 10,
      address: 'Other',
      writer: 'Dan Brown'
    }
    ],
  };
  export default data;
  